### ISSUE TITLE
Option to use yarn instead of npm

### ISSUE THREAD

**Issue by EdmundsEcho** [philschonholzer/eslint-prettier-init#48]
Thank you for putting together this mini-app.  I'm always amazed at how much time it can take to set-up prettier et al in a new project.  

The last question in the script asks whether to install using npm.  I said no because I only want to use yarn.  I have even cleaned up my global installs to only be managed by yarn.  I'm not commenting on anyone's preference, but thought it might be a useful addition to opt to use yarn if feasible.

\- E

**Comment by philschonholzer** [comment]
Thank you for the kind words. Hmm, good point. Because I only use npm I never thought of what might happen in someone only uses yarn. I'll take a look what it would mean to update the script.

**Comment by philschonholzer** [comment]
So I took a look at the problem. 

In the script I'm using `eslint --init` to setup the base config and enhance it after for prettier. The question "Would you like to install them now with npm?" is from `eslint --init` and I don't want to rewrite the eslint config myself from scratch and have to maintain it after. 

Btw if you choose "no" the dependencies are listed so that you can I them with yarn later.

**Comment by EdmundsEcho** [comment]
Thank you for the response.  It might be a useful thing to add to the installation instructions (i.e., support for yarn workaround).

So I did input "no", but the script still went ahead and triggered several installs.  Is that supposed to be the case?  i.e., if I say "no" should I expect an exit without any install?

**Comment by philschonholzer** [comment]
Yeah, I guess for yarn it is not really a great solution. The problem is, I don't know how to find out if the last question was answered with "no"... After `eslint --init` is finished I install 'prettier', 'eslint-plugin-prettier' and 'eslint-config-prettier' for prettier to work. In theory I could only add them to the package.json without installing them if someone answers "no", but as I wrote I don't know how to find out. If you have an idea I'm happy to except a PR.
